version: 2
updates:
- package-ecosystem: pip
  directory: "/tab-manager-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rich
    versions:
    - 10.0.0
    - 10.0.1
